### ISSUE TITLE
Any plans to continue this work?

### ISSUE THREAD

**Issue by JosephThePatrician** [lucidrains/magvit-pytorch#3]
Hey, that looks like a very good repository, but there were no updates for the past 2 months. Are there any plans to continue this work?

**Comment by lucidrains** [comment]
hey yea, i was about to get back into video modeling near end of the month

the authors open sourced their jax repository, no? how is the model; does it check out?

**Comment by lucidrains** [comment]
this repo is actually low priority, as I think transcribing from Jax to pytorch shouldn't be too difficult

maybe even chatgpt can do this lol

**Comment by lucidrains** [comment]
I did have a few ideas of my own I wanted to throw in there though

**Comment by JosephThePatrician** [comment]
That's great! Authors did open sourced their repo and it seems pretty good, but there are no pretrained models yet, so it is hard to say.
I actually looked through their code and I think there are some tricky parts, especially with training, but I really don't have a lot of experience to tell. 
If you are going back to this you might want to check out this [repo](https://github.com/RyuGood0/MAGVIT-pytorch), they have implemented 3D-VQGAN part of the model in pytorch. Might be pretty useful.

**Comment by lucidrains** [comment]
@JosephThePatrician hey, what's the consensus in the generative video circles? Is magvit worth the effort for a pytorch port. Or has some other paper taken the throne for SOTA. Just planning out the month of September
